
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DbOperationsService", targetNamespace = "http://assignments/", wsdlLocation = "http://127.0.0.1:10000/calcServer?wsdl")
public class DbOperationsService
    extends Service
{

    private final static URL DBOPERATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBOPERATIONSSERVICE_EXCEPTION;
    private final static QName DBOPERATIONSSERVICE_QNAME = new QName("http://assignments/", "DbOperationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:10000/calcServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBOPERATIONSSERVICE_WSDL_LOCATION = url;
        DBOPERATIONSSERVICE_EXCEPTION = e;
    }

    public DbOperationsService() {
        super(__getWsdlLocation(), DBOPERATIONSSERVICE_QNAME);
    }

    public DbOperationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBOPERATIONSSERVICE_QNAME, features);
    }

    public DbOperationsService(URL wsdlLocation) {
        super(wsdlLocation, DBOPERATIONSSERVICE_QNAME);
    }

    public DbOperationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBOPERATIONSSERVICE_QNAME, features);
    }

    public DbOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DbOperationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operations
     */
    @WebEndpoint(name = "DbOperationsPort")
    public Operations getDbOperationsPort() {
        return super.getPort(new QName("http://assignments/", "DbOperationsPort"), Operations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operations
     */
    @WebEndpoint(name = "DbOperationsPort")
    public Operations getDbOperationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://assignments/", "DbOperationsPort"), Operations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBOPERATIONSSERVICE_EXCEPTION!= null) {
            throw DBOPERATIONSSERVICE_EXCEPTION;
        }
        return DBOPERATIONSSERVICE_WSDL_LOCATION;
    }

}
