
package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Operations", targetNamespace = "http://assignments/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operations {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://assignments/Operations/updateRecordRequest", output = "http://assignments/Operations/updateRecordResponse")
    public void updateRecord(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://assignments/Operations/deleteRecordRequest", output = "http://assignments/Operations/deleteRecordResponse")
    public void deleteRecord(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://assignments/Operations/createRecordRequest", output = "http://assignments/Operations/createRecordResponse")
    public String createRecord(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0);

}
